src/Entity/Conferencier.php
<?php

namespace App\Entity;


use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\ConferencierRepository;

/**
 * @ORM\Entity(repositoryClass=ConferencierRepository::class)
 */
class Conferencier
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\Length(
     *  min=3,
     *  max=100,
     *  minMessage = "Votre nom est pas assez long",
     *  maxMessage = "Votre nom est trop long")
     * @Assert\NotBlank
     * @Assert\Regex(
     *     pattern="/\d/",
     *     match=false,
     *     message="Votre nom ne doit pas contenir de nombre"
     * )
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\Regex(
     *     pattern="/\d/",
     *     match=false,
     *     message="Votre prénom ne doit pas contenir de nombre"
     * )
     * @Assert\NotBlank 
     * @Assert\Length(
     * min=3,
     * max=100,
     * minMessage = "Votre prénom est pas assez long",
     * maxMessage = "Votre prénom est trop long")
     */
    private $prenom;

    /**
     * @ORM\Column(type="date")
     * @Assert\NotBlank
     * @Assert\Type("\DateTimeInterface")
     */
    private $date_naissance;

    /**
     * @ORM\OneToOne(targetEntity=Users::class, inversedBy="conferencier")
     * @ORM\JoinColumn(nullable=false) 
     */
    private $conferencierLieUsers;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->date_naissance;
    }

    public function setDateNaissance(\DateTimeInterface $date_naissance): self
    {
        $this->date_naissance = $date_naissance;

        return $this;
    }

    public function getConferencierLieUsers(): ?Users
    {
        return $this->conferencierLieUsers;
    }

    public function setConferencierLieUsers(Users $conferencierLieUsers): self
    {
        $this->conferencierLieUsers = $conferencierLieUsers;

        return $this;
    }
}

src/Controller/Profil/ProfilConferencierController.php
<?php

namespace App\Controller\Profil;

use App\Entity\Users;
use App\Service\Securizer;
use App\Entity\Conferencier;
use App\Form\Conferencier1Type;
use App\Repository\ConferencesRepository;
use App\Repository\ConferencierRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @IsGranted("ROLE_USER")
 * @Route("/profil/conferencier")
 */
class ProfilConferencierController extends AbstractController
{
    /**
     * @IsGranted("ROLE_USER")
     * @Route("/", name="profil_conferencier_index", methods={"GET"})
     */
    public function index(ConferencierRepository $conferencierRepository,  Securizer $securizer): Response
    {
        if($securizer->isGranted($this->getUser(), 'ROLE_ADMIN')){
            return $this->redirectToRoute('admin_accueil');
        }
        
        //dd($conferencierRepository);
        return $this->render('profil/profil_conferencier/index.html.twig', [
            'conferencier' => $conferencierRepository->find($this->getUser())           
        ]);
    }    

    /**
     * @IsGranted("ROLE_USER")
     * @Route("/{id}", name="profil_conferencier_show", methods={"GET"})
     */
    public function show(Conferencier $conferencier, Securizer $securizer): Response
    {
        if($securizer->isGranted($this->getUser(), 'ROLE_ADMIN')){
            return $this->redirectToRoute('admin_accueil');
        }

        return $this->render('profil/profil_conferencier/show.html.twig', [
            'conferencier' => $conferencier,
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @Route("/{id}/edit", name="profil_conferencier_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Conferencier $conferencier,  Securizer $securizer): Response
    {
        if($securizer->isGranted($this->getUser(), 'ROLE_ADMIN')){
            return $this->redirectToRoute('admin_accueil');
        }
        
        $form = $this->createForm(Conferencier1Type::class, $conferencier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('profil_conferencier_index');
        }

        return $this->render('profil/profil_conferencier/edit.html.twig', [
            'conferencier' => $conferencier,
            'form' => $form->createView(),
        ]);
    }   

    /**
     * @IsGranted("ROLE_USER")
     * @Route("/supprimer/{id}", name="supprimer_compte", methods={"GET","POST"})
     */
    public function delete(Request $request, Users $users, ConferencesRepository $conferencesRepository): Response
    {
        $id_user = $users->getId();

        
        $result = $conferencesRepository->findBy([
                "conferenceLieAUsers" => $id_user,
            ]);

        $images = [];
        
        foreach($result as $key => $value){

            array_push($images, $value->getImage());       
        
        }
        
        for($i = 0; $i < count($images); $i++){
            
            $img = $images[$i];
            $imagesFinale = substr($img, 7);

            $nomImage = $this->getParameter("uploadsAbsoluteDir") . $imagesFinale;

        
            if(file_exists($nomImage)){
                unlink($nomImage);
            }
            
        } 
        
        
        if ($this->isCsrfTokenValid('delete'.$users->getId(), $request->request->get('_token'))) {

            $this->container->get('security.token_storage')->setToken(null);

            $entityManager = $this->getDoctrine()->getManager();            
            $entityManager->remove($users);
            $entityManager->flush();
        }
        $this->addFlash('success', 'Votre compte utilisateur a bien été supprimé !'); 

        return $this->redirectToRoute('accueil');
    }
}

src/Controller/Profil/ProfilController.php
<?php

namespace App\Controller\Profil;

use App\Entity\Users;
use App\Form\UsersType;
use App\Service\Securizer;
use App\Entity\Conferences;
use App\Form\ConferencesType;
use App\Repository\UsersRepository;
use App\Uploader\UploaderInterface;
use App\Repository\ConferencesRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @IsGranted("ROLE_USER")
 * @Route("/profil")
 * @package App\Controller\Profil
 */
class ProfilController extends AbstractController
{

    /**
     * @IsGranted("ROLE_USER")     
     * @Route("/", name="profil_index", methods={"GET"})
     */
    public function profilIndex(Securizer $securizer): Response
    {   
        
        //gestion des rôles

        if($securizer->isGranted($this->getUser(), 'ROLE_ADMIN')){
            return $this->redirectToRoute('admin_accueil');
        }

        return $this->render('profil/accueil.html.twig');
    }
    
    /**
     * @IsGranted("ROLE_USER")     
     * @Route("/conferences", name="profil_conferences", methods={"GET"})
     */
    public function index(ConferencesRepository $conferencesRepository, Securizer $securizer): Response
    {   
        
        //gestion des rôles

        if($securizer->isGranted($this->getUser(), 'ROLE_ADMIN')){
            return $this->redirectToRoute('admin_accueil');
        }

        return $this->render('profil/index.html.twig', [
            'conferences' => $conferencesRepository->findBy([
                "conferenceLieAUsers" => $this->getUser(),
            ]),
        ]);
    }


    /**
     * @IsGranted("ROLE_USER")
     * @Route("/informations", name="modifier_vos_informations", methods={"GET", "POST"})
     */
    public function profileEdit(Request $request, UsersRepository $user, Securizer $securizer, UserPasswordEncoderInterface $passwordEncoder) : Response
    {
        //gestion des rôles
            
        if($securizer->isGranted($this->getUser(), 'ROLE_ADMIN')){
            return $this->redirectToRoute('admin_accueil');
        }
        
        $user = $this->getUser();

        $form = $this->createForm(UsersType::class, $user);
        $form->handleRequest($request);

        
        if ($form->isSubmitted() && $form->isValid()) {

            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            $this->addFlash('msg', 'Vous informations ont bien été modifiées !');
            
            return $this->redirectToRoute('profil_index');
        }

        return $this->render('profil/profilEdit.html.twig', [
            'user'=>$user,           
            'form'=> $form->createView(),
        ]);
    }
    
    /**
     * @IsGranted("ROLE_USER")
     * @Route("/new", name="creer_conference", methods={"GET","POST"})
     */
    public function new(Request $request, UploaderInterface $uploader, Securizer $securizer): Response
    {

        //gestion des rôles
        
        if($securizer->isGranted($this->getUser(), 'ROLE_ADMIN')){
            return $this->redirectToRoute('admin_accueil');
        }
        
        $conference = new Conferences();
        $form = $this->createForm(ConferencesType::class, $conference);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $file = $form->get("file")->getData();
            $conference->setImage($uploader->upload($file));

            $conference->setConferenceLieAUsers($this->getUser());
            
            
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($conference);
            $entityManager->flush();

            return $this->redirectToRoute('profil_conferences');
        }

        return $this->render('profil/new.html.twig', [
            'conference' => $conference,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @Route("/{id}", name="montrer_conference", methods={"GET"})
     */
    public function show(Conferences $conference, Securizer $securizer): Response
    {   

        
        //gestion des rôles
        
        if($securizer->isGranted($this->getUser(), 'ROLE_ADMIN')){
            return $this->redirectToRoute('admin_accueil');
        }


        return $this->render('profil/show.html.twig', [
            'conference' => $conference,
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @Route("/{id}/modifier_conference", name="modifier_conference", methods={"GET","POST"})
     */
    public function edit(Request $request, Conferences $conference,  UploaderInterface $uploader, Securizer $securizer): Response
    {

        //gestion des rôles
        
        if($securizer->isGranted($this->getUser(), 'ROLE_ADMIN')){
            return $this->redirectToRoute('admin_accueil');
        }


        $form = $this->createForm(ConferencesType::class, $conference);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $images = $conference->getImage();

            $imagesFinale = substr($images, 7);

            //dd($imagesFinale);

            $nomImage = $this->getParameter("uploadsAbsoluteDir") . $imagesFinale;

            if(file_exists($nomImage)){
                unlink($nomImage);
            }

            $file = $form->get("file")->getData();

            //Ici on récupère le fichier par le get et on envoit une (image)

            if($file !== null){
                $conference->setImage($uploader->upload($file));                

            }
            $conference->setConferenceLieAUsers($this->getUser());

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('profil_conferences');
        }

        return $this->render('profil/edit.html.twig', [
            'conference' => $conference,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @Route("/{id}", name="supprimer_conference", methods={"POST"})
     */
    public function delete(Request $request, Conferences $conference, Securizer $securizer): Response
    {

        //gestion des rôles
            
        if($securizer->isGranted($this->getUser(), 'ROLE_ADMIN')){
            return $this->redirectToRoute('admin_accueil');
        }


        if ($this->isCsrfTokenValid('delete'.$conference->getId(), $request->request->get('_token'))) {

            $images = $conference->getImage();

            $imagesFinale = substr($images, 7);

            //dd($imagesFinale);

            $nomImage = $this->getParameter("uploadsAbsoluteDir") . $imagesFinale;

            if(file_exists($nomImage)){
                unlink($nomImage);
            }
            
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($conference);
            $entityManager->flush();
        }

        return $this->redirectToRoute('profil_conferences');
    }    
}

templates/profil/profil_conferencier/_delete_form.html.twig
<form method="post" action="{{ path('supprimer_compte', {'id': conferencier.id}) }}" onsubmit="return confirm('Etes vous sûr de vouloir supprimer votre compte?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ conferencier.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/profil/profil_conferencier/_form.html.twig
<div class="container">
    <div class="row bg-white rounded m-2" id="formPlace">
        <div class="col-sm-6 col-md-6 col-lg-8">
            {{ form_start(form) }}

            <div class="form-group">
                <label class="custom-control-label" for="nom">Nom :</label>
                {{ form_widget(form.nom, { 'attr': {'class': 'form-control'} }) }}
                {{ form_errors(form.nom) }}
            </div>
            <div class="form-group">
                <label class="custom-control-label" for="nom">Prénom :</label>
                {{ form_widget(form.prenom, { 'attr': {'class': 'form-control'} }) }}
                {{ form_errors(form.prenom) }}
            </div>

            <div class="form-group date">
                <label class="custom-control-label" for="nom">Date de naissance :</label>
                {{ form_widget(form.date_naissance, { 'attr': {'class': 'date'} }) }}
                {{ form_errors(form.date_naissance) }}
            </div>

            <div class="text-center">
                <button class="btn bg-success text-white m-2">{{ button_label|default('Save') }}</button>
            </div>

            {{ form_end(form) }}
        </div>
    </div>
</div>

templates/profil/profil_conferencier/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Conferencier{% endblock %}
{% block stylesheets %}
<link rel="stylesheet" href={{ asset("css/profil/profil.css") }}>
{% endblock %}

{% block body %}

{% include "include/_navProfil.html.twig" %}

    <h1 class="text-center h1">Modifier vos informations personnelles</h1>

    {{ include('profil/profil_conferencier/_form.html.twig', {'button_label': 'Modifier'}) }}

    <div class="text-center">
    <a class="btn btn-lg btn-danger" href="{{ path('profil_conferencier_index') }}">Retour à la liste</a>
    </div>
    
{% endblock %}

templates/profil/profil_conferencier/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Conferencier accueil{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href={{ asset("css/profil/profil.css") }}>
{% endblock %}

{% block body %}
{% include "include/_navProfil.html.twig" %}
<div class="mb-2">
    <h1 class="text-center h1">Vos informations</h1>
</div>
<div class="table-responsive d-flex justify-content-center">
    <table class="table table-bordered border-primary w-75">
        <thead>
            <tr>                
                <th>Nom</th>
                <th class="cacher">Prenom</th>                
                <th>Voir plus</th>
                <th>Modifier</th>
                <th>Supprimer votre compte</th>
            </tr>
        </thead>
        <tbody>

        
            <tr>
            
                
                <td>{{ conferencier.nom }}</td>
                <td class="cacher">{{ conferencier.prenom }}</td>
                
                <td>
                    <a class="bg-dark rounded btnCustom" href="{{ path('profil_conferencier_show', {'id': conferencier.id}) }}">Détail</a>
                </td>
                <td>
                    <a class="bg-dark rounded btnCustom" href="{{ path('profil_conferencier_edit', {'id': conferencier.id}) }}">Modifier</a>
                </td>
                <td>
                    {{ include('profil/profil_conferencier/_delete_form.html.twig', {'button_label': 'Supprimer'}) }}                    
                </td>
            </tr>

        </tbody>
    </table>
</div>

    <div class="text-center">
        <a href="{{path("profil_index")}}" class="btn btn-lg btn-danger">Retour au tableau de bord</a>
    </div>
    
{% endblock %}

templates/profil/profil_conferencier/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Conferencier{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href={{ asset("css/profil/profil.css") }}>
{% endblock %}

{% block body %}
{% include "include/_navProfil.html.twig" %}

    <h1 class="text-center h1 mb-2">Vos informations personnelles en détail</h1>

<div class="table-responsive d-flex justify-content-center">
    <table class="table table-bordered border-primary w-75">
        <tbody>
        
            <tr>
                <th>Nom</th>
                <td>{{ conferencier.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ conferencier.prenom }}</td>
            </tr>
            <tr>
                <th>Date_naissance</th>
                <td>{{ conferencier.dateNaissance ? conferencier.dateNaissance|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Modifier vos informations</th>
                <td><a class="bg-dark rounded btnCustom" href="{{ path('profil_conferencier_edit', {'id': conferencier.id}) }}">Modifier</a>
                </td>
            </tr>
        </tbody>
    </table>
</div>
    
    <div class="text-center"><a class="btn btn-lg btn-danger" href="{{ path('profil_conferencier_index') }}">Retour</a></div>


    
{% endblock %}