src/Entity/Conferences.php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ConferencesRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ConferencesRepository::class)
 */
class Conferences
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     * @Assert\Length(
     * min=3,
     * max=255,
     * minMessage = "Le nom du lieu n'est pas assez long",
     * maxMessage = "Le nom du lieu est trop long")
     * @Assert\Regex(
     *     pattern="/\d/",
     *     match=false,
     *     message="Le titre ne doit pas contenir de nombre"
     * )
     */
    private $titre;

    /**
     * @ORM\Column(type="text") 
     * @Assert\NotBlank
     * @Assert\Type("string")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255) 
     */
    private $image;

    /**
     * @ORM\Column(type="datetime") 
     * @Assert\NotBlank
     * @Assert\Type("\DateTimeInterface") 
     */
    private $date_heure;

    /**
     * @ORM\ManyToOne(targetEntity=Users::class, inversedBy="conferences")
     * @ORM\JoinColumn(nullable=false)
     */
    private $conferenceLieAUsers;

    /**
     * @ORM\ManyToOne(targetEntity=Lieu::class, inversedBy="lieuLieConference", fetch="EAGER")
     * @ORM\JoinColumn(name="conference_liee_lieu_id", referencedColumnName="id")
     */
    private $conferenceLieeLieu;

    /**
     * @ORM\ManyToMany(targetEntity=Theme::class, inversedBy="themeLieConference", fetch="EAGER")
     * @ORM\JoinColumn(name="conference_id", referencedColumnName="id")
     */
    private $themesLiesConferences;

    /**
     * @Assert\NotBlank
     * @Assert\PositiveOrZero
     * @ORM\Column(type="decimal", precision=5, scale=2)
     */
    private $prix;

    public function __construct()
    {
        $this->themesLiesConferences = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getDateHeure(): ?\DateTimeInterface
    {
        return $this->date_heure;
    }

    public function setDateHeure(\DateTimeInterface $date_heure): self
    {
        $this->date_heure = $date_heure;

        return $this;
    }

    public function getConferenceLieAUsers(): ?Users
    {
        return $this->conferenceLieAUsers;
    }

    public function setConferenceLieAUsers(?Users $conferenceLieAUsers): self
    {
        $this->conferenceLieAUsers = $conferenceLieAUsers;

        return $this;
    }

    public function getConferenceLieeLieu(): ?Lieu
    {
        return $this->conferenceLieeLieu;
    }

    public function setConferenceLieeLieu(?Lieu $conferenceLieeLieu): self
    {
        $this->conferenceLieeLieu = $conferenceLieeLieu;

        return $this;
    }

    /**
     * @return Collection|Theme[]
     */
    public function getThemesLiesConferences(): Collection
    {
        return $this->themesLiesConferences;
    }

    public function addThemesLiesConference(Theme $themesLiesConference): self
    {
        if (!$this->themesLiesConferences->contains($themesLiesConference)) {
            $this->themesLiesConferences[] = $themesLiesConference;
            $themesLiesConference->addThemeLieConference($this);
        }

        return $this;
    }

    public function removeThemesLiesConference(Theme $themesLiesConference): self
    {
        if ($this->themesLiesConferences->removeElement($themesLiesConference)) {
            $themesLiesConference->removeThemeLieConference($this);
        }

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->prix;
    }

    public function setPrix(?string $prix): self
    {
        $this->prix = $prix;

        return $this;
    }
}

src/Controller/Profil/ProfilConferencierController.php
<?php

namespace App\Controller\Profil;

use App\Entity\Users;
use App\Service\Securizer;
use App\Entity\Conferencier;
use App\Form\Conferencier1Type;
use App\Repository\ConferencesRepository;
use App\Repository\ConferencierRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

/**
 * @IsGranted("ROLE_USER")
 * @Route("/profil/conferencier")
 */
class ProfilConferencierController extends AbstractController
{
    /**
     * @IsGranted("ROLE_USER")
     * @Route("/", name="profil_conferencier_index", methods={"GET"})
     */
    public function index(ConferencierRepository $conferencierRepository,  Securizer $securizer): Response
    {
        if($securizer->isGranted($this->getUser(), 'ROLE_ADMIN')){
            return $this->redirectToRoute('admin_accueil');
        }
        
        //dd($conferencierRepository);
        return $this->render('profil/profil_conferencier/index.html.twig', [
            'conferencier' => $conferencierRepository->find($this->getUser())           
        ]);
    }    

    /**
     * @IsGranted("ROLE_USER")
     * @Route("/{id}", name="profil_conferencier_show", methods={"GET"})
     */
    public function show(Conferencier $conferencier, Securizer $securizer): Response
    {
        if($securizer->isGranted($this->getUser(), 'ROLE_ADMIN')){
            return $this->redirectToRoute('admin_accueil');
        }

        return $this->render('profil/profil_conferencier/show.html.twig', [
            'conferencier' => $conferencier,
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @Route("/{id}/edit", name="profil_conferencier_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Conferencier $conferencier,  Securizer $securizer): Response
    {
        if($securizer->isGranted($this->getUser(), 'ROLE_ADMIN')){
            return $this->redirectToRoute('admin_accueil');
        }
        
        $form = $this->createForm(Conferencier1Type::class, $conferencier);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('profil_conferencier_index');
        }

        return $this->render('profil/profil_conferencier/edit.html.twig', [
            'conferencier' => $conferencier,
            'form' => $form->createView(),
        ]);
    }   

    /**
     * @IsGranted("ROLE_USER")
     * @Route("/supprimer/{id}", name="supprimer_compte", methods={"GET","POST"})
     */
    public function delete(Request $request, Users $users, ConferencesRepository $conferencesRepository): Response
    {
        $id_user = $users->getId();

        
        $result = $conferencesRepository->findBy([
                "conferenceLieAUsers" => $id_user,
            ]);

        $images = [];
        
        foreach($result as $key => $value){

            array_push($images, $value->getImage());       
        
        }
        
        for($i = 0; $i < count($images); $i++){
            
            $img = $images[$i];
            $imagesFinale = substr($img, 7);

            $nomImage = $this->getParameter("uploadsAbsoluteDir") . $imagesFinale;

        
            if(file_exists($nomImage)){
                unlink($nomImage);
            }
            
        } 
        
        
        if ($this->isCsrfTokenValid('delete'.$users->getId(), $request->request->get('_token'))) {

            $this->container->get('security.token_storage')->setToken(null);

            $entityManager = $this->getDoctrine()->getManager();            
            $entityManager->remove($users);
            $entityManager->flush();
        }
        $this->addFlash('success', 'Votre compte utilisateur a bien été supprimé !'); 

        return $this->redirectToRoute('accueil');
    }
}

src/Controller/Profil/ProfilController.php
<?php

namespace App\Controller\Profil;

use App\Entity\Users;
use App\Form\UsersType;
use App\Service\Securizer;
use App\Entity\Conferences;
use App\Form\ConferencesType;
use App\Repository\UsersRepository;
use App\Uploader\UploaderInterface;
use App\Repository\ConferencesRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Security\Core\Authentication\Token\TokenInterface;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @IsGranted("ROLE_USER")
 * @Route("/profil")
 * @package App\Controller\Profil
 */
class ProfilController extends AbstractController
{

    /**
     * @IsGranted("ROLE_USER")     
     * @Route("/", name="profil_index", methods={"GET"})
     */
    public function profilIndex(Securizer $securizer): Response
    {   
        
        //gestion des rôles

        if($securizer->isGranted($this->getUser(), 'ROLE_ADMIN')){
            return $this->redirectToRoute('admin_accueil');
        }

        return $this->render('profil/accueil.html.twig');
    }
    
    /**
     * @IsGranted("ROLE_USER")     
     * @Route("/conferences", name="profil_conferences", methods={"GET"})
     */
    public function index(ConferencesRepository $conferencesRepository, Securizer $securizer): Response
    {   
        
        //gestion des rôles

        if($securizer->isGranted($this->getUser(), 'ROLE_ADMIN')){
            return $this->redirectToRoute('admin_accueil');
        }

        return $this->render('profil/index.html.twig', [
            'conferences' => $conferencesRepository->findBy([
                "conferenceLieAUsers" => $this->getUser(),
            ]),
        ]);
    }


    /**
     * @IsGranted("ROLE_USER")
     * @Route("/informations", name="modifier_vos_informations", methods={"GET", "POST"})
     */
    public function profileEdit(Request $request, UsersRepository $user, Securizer $securizer, UserPasswordEncoderInterface $passwordEncoder) : Response
    {
        //gestion des rôles
            
        if($securizer->isGranted($this->getUser(), 'ROLE_ADMIN')){
            return $this->redirectToRoute('admin_accueil');
        }
        
        $user = $this->getUser();

        $form = $this->createForm(UsersType::class, $user);
        $form->handleRequest($request);

        
        if ($form->isSubmitted() && $form->isValid()) {

            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($user);
            $entityManager->flush();

            $this->addFlash('msg', 'Vous informations ont bien été modifiées !');
            
            return $this->redirectToRoute('profil_index');
        }

        return $this->render('profil/profilEdit.html.twig', [
            'user'=>$user,           
            'form'=> $form->createView(),
        ]);
    }
    
    /**
     * @IsGranted("ROLE_USER")
     * @Route("/new", name="creer_conference", methods={"GET","POST"})
     */
    public function new(Request $request, UploaderInterface $uploader, Securizer $securizer): Response
    {

        //gestion des rôles
        
        if($securizer->isGranted($this->getUser(), 'ROLE_ADMIN')){
            return $this->redirectToRoute('admin_accueil');
        }
        
        $conference = new Conferences();
        $form = $this->createForm(ConferencesType::class, $conference);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $file = $form->get("file")->getData();
            $conference->setImage($uploader->upload($file));

            $conference->setConferenceLieAUsers($this->getUser());
            
            
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($conference);
            $entityManager->flush();

            return $this->redirectToRoute('profil_conferences');
        }

        return $this->render('profil/new.html.twig', [
            'conference' => $conference,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @Route("/{id}", name="montrer_conference", methods={"GET"})
     */
    public function show(Conferences $conference, Securizer $securizer): Response
    {   

        
        //gestion des rôles
        
        if($securizer->isGranted($this->getUser(), 'ROLE_ADMIN')){
            return $this->redirectToRoute('admin_accueil');
        }


        return $this->render('profil/show.html.twig', [
            'conference' => $conference,
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @Route("/{id}/modifier_conference", name="modifier_conference", methods={"GET","POST"})
     */
    public function edit(Request $request, Conferences $conference,  UploaderInterface $uploader, Securizer $securizer): Response
    {

        //gestion des rôles
        
        if($securizer->isGranted($this->getUser(), 'ROLE_ADMIN')){
            return $this->redirectToRoute('admin_accueil');
        }


        $form = $this->createForm(ConferencesType::class, $conference);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $images = $conference->getImage();

            $imagesFinale = substr($images, 7);

            //dd($imagesFinale);

            $nomImage = $this->getParameter("uploadsAbsoluteDir") . $imagesFinale;

            if(file_exists($nomImage)){
                unlink($nomImage);
            }

            $file = $form->get("file")->getData();

            //Ici on récupère le fichier par le get et on envoit une (image)

            if($file !== null){
                $conference->setImage($uploader->upload($file));                

            }
            $conference->setConferenceLieAUsers($this->getUser());

            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('profil_conferences');
        }

        return $this->render('profil/edit.html.twig', [
            'conference' => $conference,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @IsGranted("ROLE_USER")
     * @Route("/{id}", name="supprimer_conference", methods={"POST"})
     */
    public function delete(Request $request, Conferences $conference, Securizer $securizer): Response
    {

        //gestion des rôles
            
        if($securizer->isGranted($this->getUser(), 'ROLE_ADMIN')){
            return $this->redirectToRoute('admin_accueil');
        }


        if ($this->isCsrfTokenValid('delete'.$conference->getId(), $request->request->get('_token'))) {

            $images = $conference->getImage();

            $imagesFinale = substr($images, 7);

            //dd($imagesFinale);

            $nomImage = $this->getParameter("uploadsAbsoluteDir") . $imagesFinale;

            if(file_exists($nomImage)){
                unlink($nomImage);
            }
            
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($conference);
            $entityManager->flush();
        }

        return $this->redirectToRoute('profil_conferences');
    }    
}

templates/profil/_delete_form.html.twig
<form method="post" action="{{ path('supprimer_conference', {'id': conference.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cet élément ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ conference.id) }}">
    <button class="btn bg-danger text-white">Supprimer la conférence</button>
</form>

templates/profil/_form.html.twig
<div class="container">

    <div class="row center">
            <div class="col-sm-8 col-md-8 col-lg-9 m-2 text-center bg-white">
            
        {{ form_start(form) }}

        <div class="form-group mb-2">
            <label for="titre" class="col-sm-2 col-form-label">Titre :</label>
            {{ form_widget(form.titre, {'attr': {"class" : "form-control form-control-sm"}}) }}
            {{ form_errors(form.titre) }}
        </div>
        <div class="form-group mb-2">
            <label for="msg">Description :</label>
            {{form_widget(form.description, {'attr': {"class" : "form-control form-control-sm"}})}}
            {{ form_errors(form.description) }}
        </div>
        <div class="form-group mb-2 custom-file">
            <label for="" class="custom-control-label">Image :</label>
            {{ form_widget(form.file) }}
        </div>
        <div class="form-group mb-2 date">
            <label for="date_heure" class="custom-control-label">Choisir la date et l'heure :</label>
            
            {{ form_widget(form.date_heure, {'attr': {"class" : "form-control d-flex flex-row m-1", "type": "datetime-local"}}) }}
            {{ form_errors(form.date_heure) }}
            
        </div>
        <div class="form-group mb-2">
            <label for="lieu" class="custom-control-label">Lieu :</label>
            {{ form_widget(form.conferenceLieeLieu, {'attr': {"class" : "form-select"}}) }}
            {{ form_errors(form.conferenceLieeLieu) }}
        </div>
        <div class="form-group  mb-2">
            <div class="d-flex flex-column">
            <label for="theme" class="custom-control-label">Thème :</label>                
            {{ form_widget(form.themesLiesConferences, {'attr': {"class" : "key custom-control-input"}}) }}                
            {{ form_errors(form.themesLiesConferences) }}                
            </div>
        </div>
        <div class="form-group mb-2">
            <div class="d-flex flex-column">

                <label for="prix" "custom-control-label">Prix :</label>
                {{ form_widget(form.prix, {'attr': {"class" : "form-control w-25 mx-auto"}}) }}
                {{ form_errors(form.prix) }}
                
            </div>
        </div>
        <button class="btn btn-lg btn-success m-2">{{ button_label|default('Créer') }}</button>
        {{ form_end(form) }}

        </div>
    </div>
    
</div>

templates/profil/accueil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href={{ asset("css/profil/profil.css") }}>
{% endblock %}


{% block body %}

{% include "include/_navProfil.html.twig" %}

{% for message in app.flashes('message') %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>{{ message }}</strong>  
</div>
{% endfor %}
{% for message in app.flashes('msg') %}
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>{{ message }}</strong>  
</div>
{% endfor %}

<h1 class="text-center h1">Tableau de bord conférencier</h1>

<div class="container">



    <div class="mt-3 text-center">
        <strong class="h4">Bonjour, {{ app.user.conferencier.nom }} {{ app.user.conferencier.prenom }}</strong>
    </div>

    <div class="d-flex flex-column mt-4">
      
        <div class="d-flex justify-content-center mt-4"><a href="{{path("profil_conferences")}}" class="btn btn-lg btn-warning">Voir vos conférences</a>
        </div>
        <div class="d-flex justify-content-center mt-4"><a href="{{path("creer_conference")}}" class="btn btn-lg btn-warning">Créer une conférence</a>
        </div>
        <div class="d-flex justify-content-center mt-4"><a href="{{path("modifier_vos_informations")}}" class="btn btn-lg btn-warning">Modifier vos informations de connexion</a>
        </div>
        <div class="d-flex justify-content-center mt-4"><a href="{{path("profil_conferencier_index")}}" class="btn btn-lg btn-warning">Modifier vos informations personnelles</a>
        </div>        
      </div>
    </div>

    <p class="d-flex justify-content-center mt-4" ><a href="{{path("app_logout")}}" class="btn btn-lg btn-danger">Déconnexion</a></p>

</div>
{% endblock %}

templates/profil/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier une Conférence{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href={{ asset("css/profil/profil.css") }}>
{% endblock %}

{% block body %}
{% include "include/_navProfil.html.twig" %}

    <h1 class="text-center h1">Modifier une conférences</h1>

    {{ include('profil/_form.html.twig', {'button_label': 'Modifier'}) }}


    <div class="text-center">
    {{ include('profil/_delete_form.html.twig') }}
    
    <a href="{{ path('profil_conferences') }}" class="btn btn-lg btn-dark m-2">Retour à la liste</a>

    </div>
{% endblock %}

templates/profil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Conférences index{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href={{ asset("css/profil/profil.css") }}>
{% endblock %}

{% block body %}
{% include "include/_navProfil.html.twig" %}
    <h1 class="text-center h1">Conférences de {{ app.user.conferencier.nom }} {{ app.user.conferencier.prenom }}</h1>

<div class="table-responsive d-flex justify-content-center">
    <table class="table table-bordered border-primary w-75 text-center">
    
        <thead>
            <tr>
                <th>Titre</th>                
                <th>Image</th>
                <th class="cacher">Date et heure</th>
                <th>Voir plus</th>
                <th>Modifier</th>
            </tr>
        </thead>
        <tbody>
        {% for conference in conferences %}
            <tr>
                <td>{{ conference.titre }}</td>                
                <td><img src="{{ asset(conference.image) }}" class="img-fluid" width="180"alt="affiche de la conférence"></td>
                <td class="cacher">{{ conference.dateHeure ? conference.dateHeure|date('d-m-Y H:i:s') : '' }}</td>
                <td>
                    <a class="bg-primary rounded btnCustom" href="{{ path('montrer_conference', {'id': conference.id}) }}">Détail</a>
                </td>
                <td>
                    <a class="bg-dark rounded btnCustom" href="{{ path('modifier_conference', {'id': conference.id}) }}">Modifier</a>
                </td>
                
                
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<div class="text-center">
    <a href="{{ path('creer_conference') }}" class="btn btn-lg btn-success m-1">Créer une conférence</a>
    <a href="{{path("profil_index")}}" class="btn btn-lg btn-danger m-1">Retour au tableau de bord</a>
</div>

{% endblock %}

templates/profil/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle Conférence{% endblock %}
{% block stylesheets %}
<link rel="stylesheet" href={{ asset("css/profil/profil.css") }}>
{% endblock %}

{% block body %}
{% include "include/_navProfil.html.twig" %}

    <h1 class="text-center h1">Créer une Conférence</h1>

    {{ include('profil/_form.html.twig') }}

    <div class="text-center">
        <a href="{{ path('profil_conferences') }}" class="btn btn-lg btn-danger m-2">Retour à la liste</a>
    </div>
    
{% endblock %}

templates/profil/profilEdit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modification des informations de connexion{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href={{ asset("css/profil/profil.css") }}>
{% endblock %}

{% block body %}
{% include "include/_navProfil.html.twig" %}

<h1 class="text-center h1">Modification des informations de connexion</h1>

<div class="container">
    <div class="row bg-white rounded m-2" id="formPlace">
        <div class="col-sm-6 col-md-6 col-lg-8">

            {{ form_start(form) }}
            <div class="form-group">
                <label class="custom-control-label" for="email">Votre email :</label>
                {{ form_widget(form.email, { 'attr': {'class': 'form-control'} }) }}
                {{ form_errors(form.email) }}
            </div>
            <div class="form-group">
                <label for="password" class="col-sm-2 col-form-label">Mot de passe :</label>
                {{ form_widget(form.plainPassword.first, {
                'attr': {'class': 'form-control'}
                }) }}
                {{ form_errors(form.plainPassword.first) }}
            </div>
            <div class="form-group">
                <label class="custom-control-label" for="">Confirmez votre mot de passe :</label>
                {{ form_widget(form.plainPassword.second, {
                'attr': {'class': 'form-control'}
                }) }}
                {{ form_errors(form.plainPassword.second) }}
            </div>
            <div class="text-center m-2">
                <button type="submit" class="btn btn-primary">Modifier</button>
            </div>
            {{ form_end(form) }}

        </div>
    </div>
</div>

<div class="text-center">
    <a href="{{path("profil_index")}}" class="btn btn-lg btn-danger">Retour au tableau de bord</a>
</div>

{% endblock %}

templates/profil/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Conferences{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href={{ asset("css/profil/profil.css") }}>
{% endblock %}


{% block body %}
{% include "include/_navProfil.html.twig" %}

    <h1 class="text-center h1">Conférence : {{ conference.titre }}</h1>

    <div class="container">

    <div class="row justify-content-center">
        <div class="col-sm-8 col-md-8 col-lg-9 text-center d-flex justify-content-center">

            <div class="card m-4 bg-light" style="width: 35rem;">

                <h4 class="text-center">Thème(s) : 
                {% for theme in conference.themesLiesConferences %}
                    -{{theme.nom}}
                {% endfor %}
                </h4>

                <img src="{{ asset(conference.image) }}" width="275" class="card-img-top"
                    alt="affiche de la conférence">
                <div class="card-body">
                    <h3 class="card-title">{{ conference.titre }}</h3>

                    <h5 id="description" class="text-center"> Descriptif </h5>
                    
                    <p class="card-text">{{ conference.description }}</p>
                    <p class="text-center text-primary font-weight-bold">Organisé à : {{ conference.conferenceLieeLieu.ville }} </p>
                    <p class="text-center text-primary font-weight-bold">Au : {{ conference.conferenceLieeLieu.nom }} </p>
                    <p class="text-center text-primary font-weight-bold">Adresse : {{ conference.conferenceLieeLieu.adresse }} </p>

                    <p class="card-text"><strong class="text-success">Date et heure : {{ conference.dateHeure ? conference.dateHeure|date('d-m-Y
                            H:i:s') : ''
                            }}</strong></p>

                <p class="text-center"><strong>Prix du ticket d'entée : {{ conference.prix }} €</strong></p>
                
                    
                </div>
            </div>

        </div>
    </div>
</div>

    <div class="d-flex justify-content-center align-items-center">
    <a href="{{ path('profil_conferences') }}" class="btn btn-lg btn-dark m-1">Retour à la liste</a>

    <a href="{{ path('modifier_conference', {'id': conference.id}) }}" class="btn btn-lg btn-warning m-1">Modifier</a>

    {{ include('profil/_delete_form.html.twig') }}

    </div>

{% endblock %}